bcre/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls
urlpatterns = [
    path('',include('pages.urls')),
    path('listings/', include('listings.urls')),
    path('contacts/', include('contacts.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + debug_toolbar_urls()

listings/models.py
from django.db import models
from realtors.models import Realtor
from datetime import datetime
from listings.choices import district_choices

# Create your models here.
class Listing(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    street = models.CharField(max_length=200)
    district = models.CharField(max_length=50, choices=district_choices.items())
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    clubhouse = models.IntegerField()
    sqft = models.IntegerField()
    estate_size = models.FloatField(default=0.0)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)

    def __str__(self):
        return f"House Title: {self.title}"

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %} | About {% endblock %}
{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">About BC Real Estate</h1>
          <p class="lead">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
            pariatur!
          </p>
        </div>
      </div>
    </div>
  </section>
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            
            <a href={% url "index" %}> <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active">About</li>
        </ol>
      </nav>
    </div>
  </section>
  <section id="about" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h2>We Search For The Perfect Home</h2>
          <p class="lead">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt,
            pariatur!
          </p>
          <img src={% static "img/about.jpg" %} alt="" />
          <p class="mt-4">
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Perspiciatis esse officia repudiandae ad saepe ex, amet neque quod
            accusamus rem quia magnam magni dolorum facilis ullam minima
            perferendis? Exercitationem at quaerat commodi id libero eveniet
            harum perferendis laborum molestias quia.
          </p>
        </div>
        {% comment %} modify mvp {% endcomment %}
        {% if mvp_realtors %}
        
        <div class="col-md-4">
          {% for realtor in mvp_realtors %}
          <div class="card">
            <img
              class="card-img-top"
              {% comment %} fix image later {% endcomment %}
              src={{realtor.photo.url}}
              alt="Seller of the month"
            />
            <div class="card-body">
              <h5 class="card-title">Seller Of The Month</h5>
              <h6 class="text-secondary">{{realtor.name}}</h6>
              <p class="card-text">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis
                nesciunt amet, illo itaque similique repellat. content.
              </p>
            </div>
          </div>
          {% endfor %}
        </div>
        
        
        {% endif %}
      </div>
    </div>
  </section>
  <section id="work" class="bg-dark text-white text-center">
    <h2 class="display-4">We Work For You</h2>
    <h4>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem velit
      aperiam, unde aliquid at similique!
    </h4>
    <hr />
    <a href={% url 'listings' %} class="btn btn-secondary text-white btn-lg"
      >View Our Featured Listings</a
    >
  </section>
  <section id="team" class="py-5">
    <div class="container">
      <h2 class="text-center">Our Team</h2>
      <div class="row text-center">
        {% if realtors %}
        {% for realtor in realtors %}
        <div class="col-md-4">
          <img
          {% comment %} fix image later {% endcomment %}
            src={{realtor.photo.url}}
            alt=""
            class="rounded-circle mb-3"
          />
          <h4>{{realtor.name}}</h4>
          <p class="text-success">
            <i class="fas fa-award text-success mb-3"></i> Realtor
          </p>
          <hr />
          <p><i class="fas fa-phone"></i> {{realtor.phone}}</p>
          <p><i class="fas fa-envelope-open"></i> {{realtor.email}}</p>
        </div>

        
        {% endfor %}
        {% else %}
        <div>
          <p>No Realtor Available</p>
        </div>
        {% endif %}
      </div>
    </div>
  </section>
{% endblock %}

templates/pages/index.html
{% extends 'base.html'%} {% load humanize %} 
{% block title %} | Welcome {% endblock %}
{% block content%}
<section id="showcase">
      <div class="container text-center">
        <div class="home-search p-5">
          <div class="overlay p-5">
            <h1 class="display-4 mb-4">Property Searching Just Got So Easy</h1>
            <p class="lead">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit.
              Recusandae quas, asperiores eveniet vel nostrum magnam voluptatum
              tempore! Consectetur, id commodi!
            </p>
            <div class="search">
              {% comment %} need to fix search.html and change to POST{% endcomment %}
              <form action={% url 'search' %} method="GET">
                <!-- Form Row 1 -->
                <div class="form-row">
                  <div class="col-md-4 mb-3">
                    <label class="sr-only">Keywords</label>
                    <input
                      type="text"
                      name="keywords"
                      class="form-control"
                      placeholder="Keyword (Bathrooms, ClubHouse, etc)"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">title</label>
                    <input
                      type="text"
                      name="title"
                      class="form-control"
                      placeholder="Title"
                    />
                  </div>

                  <div class="col-md-4 mb-3">
                    <label class="sr-only">District</label>
                    <select name="district" class="form-control">
                      <option selected="true" disabled="disabled">
                        District (All)
                      </option>
                      {% for key,value in district_choices.items %}
                      <option value={{key}}>{{value}}</option>
                      
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <!-- Form Row 2 -->
                <div class="form-row">
                  <div class="col-md-6 mb-3">
                    <label class="sr-only">Bedrooms</label>
                    <select name="bedrooms" class="form-control">
                      <option selected="true" disabled="disabled">
                        Bedrooms (All)
                      </option>
                      {% for key,value in bedroom_choices.items %}
                      <option value={{key}}>{{value}}</option>
                      
                      {% endfor %}
                    </select>
                  </div>
                  <div class="col-md-6 mb-3">
                    <select name="price" class="form-control" id="type">
                      <option selected="true" disabled="disabled">
                        Max Price (Any)
                      </option>
                      {% for key,value in price_choices.items %}
                      <option value={{key}}>{{value}}</option>
                      
                      {% endfor %}
                    </select>
                  </div>
                </div>
                <button class="btn btn-secondary btn-block mt-4" type="submit">
                  Submit form
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
 </section>
    <section id="listings" class="py-5">
        <div class="container">
          {% include 'partials/_alert.html' %}
          <h3 class="text-center mb-3">Latest Listings</h3>
          <div class="row">
            {% if listings %}
            {% for listing in listings%}
            <!-- Listing 1 -->
            <div class="col-md-6 col-lg-4 mb-4">
              <div class="card listing-preview">
                <img
                  class="card-img-top"
                  {% comment %} dynamic data, need to fix {% endcomment %}
                  src={{listing.photo_main.url}}
                  alt=""
                />
                <div class="card-img-overlay">
                  <h2>
                    <span class="badge badge-secondary text-white"
                      >${{listing.price | intcomma }}</span
                    >
                  </h2>
                </div>
                <div class="card-body">
                  <div class="listing-heading text-center">
                    <h4 class="text-primary">{{listing.title | title }}</h4>
                    <p>
                      <i class="fas fa-map-marker text-secondary"></i> {{listing.get_district_display}}
                      
                    </p>
                  </div>
                  <hr />
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-th-large"></i> Sqft: {{listing.sqft | intcomma }}
                    </div>
                    <div class="col-6">
                      <i class="fas fa-dumbbell"></i> ClubHouse: {{listing.clubhouse}}
                    </div>
                  </div>
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-bed"></i> Bedrooms: {{listing.bedrooms}}
                    </div>
                    <div class="col-6">
                      <i class="fas fa-bath"></i> Bathrooms: {{listing.bathrooms}}
                    </div>
                  </div>
                  <hr />
                  <div class="row py-2 text-secondary">
                    <div class="col-6"><i class="fas fa-user"></i> {{listing.realtor}}</div>
                  </div>
                  <div class="row text-secondary pb-2">
                    <div class="col-6">
                      <i class="fas fa-clock"></i> {{listing.list_date | timesince}}
                    </div>
                  </div>
                  <hr />
                  <a href={% url "listing" listing.id %} class="btn btn-primary btn-block"
                    >More Info</a
                  >
                </div>
              </div>
            </div>
            {% endfor%}
            {% else %}
            <div class="col-md-12">
              <p>No Listing Available</p>
            </div>
            {% endif %}
  
            <!-- Listing 2 -->
            
  
            <!-- Listing 3 -->
            
          </div>
        </div>
      </section>
      <section id="services" class="py-5 bg-secondary text-white">
        <div class="container">
          <div class="row text-center">
            <div class="col-md-4">
              <i class="fas fa-comment fa-4x mr-4"></i>
              <hr />
              <h3>Consulting Services</h3>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
                debitis nam! Repudiandae, provident iste consequatur hic
                dignissimos ratione ea quae.
              </p>
            </div>
            <div class="col-md-4">
              <i class="fas fa-home fa-4x mr-4"></i>
              <hr />
              <h3>Propery Management</h3>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
                debitis nam! Repudiandae, provident iste consequatur hic
                dignissimos ratione ea quae.
              </p>
            </div>
            <div class="col-md-4">
              <i class="fas fa-suitcase fa-4x mr-4"></i>
              <hr />
              <h3>Renting & Selling</h3>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt,
                debitis nam! Repudiandae, provident iste consequatur hic
                dignissimos ratione ea quae.
              </p>
            </div>
          </div>
        </div>
      </section>
{% endblock%}